#if !DISABLE_CHEAT_MANAGER
using System;
using Scripts.Initialize;
using Scripts.UI.Background;
using UnityEngine;


namespace Scripts.Cheat
{
    public class CheatManager : AutoGeneratedSingletonMonoBehaviour<CheatManager>
    {
        private void Update()
        {
            if (Input.GetKeyDown(KeyCode.O))
            {
                BackgroundHandler.Instance.DecreaseBackgroundIndex();
            }
            else if (Input.GetKeyDown(KeyCode.P))
            {
                BackgroundHandler.Instance.IncreaseBackgroundIndex();
            }
        }
    }
}
#endif